server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: gateway_route   #我们自定义的路由 ID，保持唯一
          uri: http://www.baidu.com   #目标服务地址
          predicates:  #路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
            - Path=/